---
title: "Themes, projects and skills"
---

{{< include proje.svg >}}

Feel free to contact me if you want to encourage or comment on some of the themes, projects or skills in the graph or if you are aware of any funding opportunities.

Below is a short (sometimes a bit longer) description of projects in the graph above. s

### 201) Existential risk demonstrator (website)

See link for more info: https://villeseppala.wordpress.com/2025/07/07/website-concept-for-visualizing-existential-risk-looking-for-feedback-funding/

In short, the site allows the users to input values for existential risk probability for various time periods (or survival probability at given points). It then calculates the expected longevity of humankind (measured in expected years the humankind will live or in expected human lives. The graphs show the results in both the condensed and linear time scales. The motivation behind the site is to demonstrate that even very small improvements in existential risk will pay off immensely in the long run.

### 202) How should we evaluate the threat levels of specific existential risks? (Text)

(medium size text, possibly an article)

Related to project 201.

Most studies that concern individual existential risk ask the respondents to estimate the probability from them causing humankind's extinction or other catastrophic outcome. There are major issues with this approach, sometimes noted in the literature. Risks are intertwined and it is difficult to determine what is the threshold of contribution from a specific threat for it to be considered as a cause for an extinction/catastrophic event.

To illustrate: If an extinction event is caused by a misaligned AI using nuclear weapons, is it an AI or nuclear extinction? Most of the time in the literature it is allowed to be both. But if AI is used only very partially, in a very mundane capacity, does it still count? Climate change poses even bigger complexity? It is very unlikely that climate change in itself would cause extintction, but it may increase the probability of major conflicts. Therefore, it could be a major factor behind extinction even if it wasn’t the final cause. But often in the literature it seems that this is not taken into account in the threat estimates from climate change.

Toby Ord explores these issues to some extent in Precipice (2020) and talks about risk factors that influence the risks themselves. I would like to explore this further and consider if it would be wise to evalute the threat from specific risks by asking how much the removal of a threat (risk factor) altogether would reduce the overall existential/catastrophic risk probability. The classification of these . This estimate would indicate the overall impact of a threat (regardless of how deeply entrenched the threat is), while taking into account the impact from other threats (avoid double counting). Focus on risk factors and their reduction would also be a more policy relevant approach.

I think that there are two ways to estimate the risk reduction probability. Firstly, in percentage points, as absolute reduction. In this case, if a threat was totally uncorrelated to other threats (such as m maybe asteroid impacts), the reduction estimate would also correspond to the standard risk probability estimate from the risk.

Second way is to estimate the reduction relative to the overall risk probability, a percentage reduction than a percentage point reduction. This could be preferable especially if the overall risk is hard to estimate but the relative magnitude of the specific risk relative to others, and the risk interaction to relative to them, is clearer. Questionnaires could be built to accomodate both ways.

### 203) Overlapping tariff unions as a global political tool (text)

(medium size text, possibly article)

I feel that when punititive tariffs are used, they are usually set unilaterally, and based on general disagreements between two countries. They might lead to a chain of retalitaory tariffs and worsen relations between countries even more.

Encouraging countries to set tariffs based on specific issues instead of specific countries could be more productive. The tariff setter would have to specify a measurable topic the tariff is based on and could not hide behind ambiguity. This would also let the world to better evaluate how fair the tariffs are. The tariff receiver would know what to change in order to get the tariffs taken off or reduced.

This could help to move the world from blocs and into overlapping tariff unions. Setting tariffs would become less dramatic, more business as usual. This could relieve retalitaory pressure.

This would bring the tariff topics more into international and national political discussion.

Tariff unions could decide on how much . Not sure yet if it would be optimal to let countries set within unions to set tariff rates separately, or would it be better if the rates were equal. s

EU is setting carbon border adjustment mechanism. WTO proof. Could broaden to a tariff union on carbon.

### 204) Manifesto on us being the most important generations in history (text)

(very long text, possibly a book)

Would consist of these chapters, according to my current plans:

-   Humankind's great future
-   Current fragility of the great future
-   Our great power and responsibility in guiding humanity over the fragile times
-   What makes us passive despite our power and responsibility
-   Some things that I think should be done, policy wise
-   

### 205) Tool for demonstrating possible national EU emission goals (website)

EU Climate architecture following year 2030 is currently under being planned and there are several options of approach. Regardless of the sectoral divisions, there will probably be some kind of national targets, such as there currently are for effort sharing sector and land use, land use change and forestry sector. I could buile a website that would allow the user to set an EU wide goal and then divide it to national emission goals, either manually or through some .

### 206) Carbon pricing - basics and benefits (video)

Carbon pricing is an efficient way to reduce emissions, but causes a direct cost to consumers, which often . I’d like to make a video that explains the efficiency of carbon pricing and its benefits as a way to create.

A portion of the video would explore global carbon pricing and dividend, using my website.

### 207) Incentivizing built of new electricity interconnectors across Europe (text)

(Shorter text, a blog)

##### Problem and motivation

Sweden and Norway (hereafter, the North) have shown resistance to building new power interconnectors to Central Europe. (links here). They would increase the average electricity prices in these countries, since there is more demand for electricity in the Central Europe. However, they would benefit Europe as a whole. The population weighted decrease in electricity prices in Central Europe would be greater than the increase in the North.

Decreasing electricity prices across Europe is important for Europe's industrial competetiveness.

Could EU or the European countries within the same power market create a system to encourage building new interconnectors?

##### My suggested solution (in progress)

My idea for this: Countries who import electricity at any moment would pay to the countries that export it to them? The size of payment would be determined by the contrafactual electricity prices for the case that there was no interconnector between the countries. This indicates the benefit of the interconnector to the importer and the harm to the exporter. The payment would not be 100% of the difference, since the exporting country benefits by having a greater power generation industry to tax. And because their own prices increase less than is the decrease in importing country.

This soluction would also incentivize countries to remove bureaucratical barriers from building new electricity generation if it is cheaper than payments to importers. Would decrease average electricity prices.

This would incentivize building flexible power generation wherever possible, since it would fetch a better price than currently. Which would decrease average prices.

The momentary wind energy production varies a lot more across Europe than across a single country. Stronger power connections between countries would help to balance this variation. This would make wind energy capture rates be higher. It is important that we can take the max. benefit from wind energy, since it is so cheap to produce.

They would incentivize countries to build steady production electricity, since that would decrease their dependence from exporting countries when electricity is expensive.

### 208) Pumped-storage hydro power in Finland (text)

(medium size text, possibly an article)

Would pumped-storage hydro power be a good solution for Finland? Considering some of the following aspects:

-   Economic benefits. What would be the effect on energy prices. Would the projects need government support?
-   How much room is there for capacity?
-   How much harm would it cause to nature and how much resources need? Compared to regular hydro and battey storage solutions.

Currently, I think so.

### 209) Circle graph creator (website)

I have made several Nightingale/radial plots for comparing countries across different topics/outcomes. Some can be seen here: https://villeseppala.wordpress.com/pictures-and-animations/

I’d like to make producing them more automatic and produce a website for it, so that the user can select what outcome variable to look at, how to group countries (color the bars), and what year to compare to track change over time.

### 210) Homepage (website)

Creating a homepage. Currently using wordpress for my website at villeseppala.fi. Quarto/Markdown based website would allow more flexibility and better use of ggplot2 graphs.

#### 
